In [16]:
import pandas as pd

path = 'C:\\Users\\alissonsilva\\Downloads\\'
file_one = 'fp_modelo.csv'
file_two = 'fp_modelo_12.csv'


df1 = pd.read_csv(path + file_one, header=None)
df2 = pd.read_csv(path + file_two, header=None)

In [21]:
df2

,0,1,2,3,4,5
0,1,1,038003-2,Integra GS 1.8,Dezembro/2019,Integra
1,2,1,038002-4,Legend 3.2/3.5,Dezembro/2019,Legend
2,3,1,038001-6,NSX 3.0,Dezembro/2019,NSX
3,4,2,060001-6,MARRUÁ 2.8 12V 132cv TDI Diesel,Dezembro/2019,MARRUA
4,5,3,006009-7,145 Elegant 1.7/1.8 16V,Dezembro/2019,145
...,...,...,...,...,...,...
8798,8940,56,002190-3,YARIS XS Connect 1.5 Flex 16V 5p Aut.,Dezembro/2019,YARIS
8799,8941,56,002191-1,YARIS XS Connect Sedan 1.5 Flex 16V Aut.,Dezembro/2019,YARIS
8800,8942,56,002192-0,YARIS X-WAY Connect 1.5 Flex 16V 5p Aut.,Dezembro/2019,YARIS
8801,8943,59,005519-0,Golf GTE TSI 1.4 16V Híbrido Aut.,Dezembro/2019,Golf
8802,8944,114,513324-6,P-410 A 6x2 2p (diesel)(E5),Dezembro/2019,P-410

In [23]:
df = df1.merge(df2, on=2, how='left', suffixes=('_novo', '_velho'))
df

,0_novo,1_novo,2,3_novo,4_novo,5_novo,0_velho,1_velho,3_velho,4_velho,5_velho
0,1,1,038003-2,Integra GS 1.8,NaN,NaN,1.0,1.0,Integra GS 1.8,Dezembro/2019,Integra
1,2,1,038002-4,Legend 3.2/3.5,NaN,NaN,2.0,1.0,Legend 3.2/3.5,Dezembro/2019,Legend
2,3,1,038001-6,NSX 3.0,NaN,NaN,3.0,1.0,NSX 3.0,Dezembro/2019,NSX
3,4,2,060001-6,MARRUÁ 2.8 12V 132cv TDI Diesel,NaN,NaN,4.0,2.0,MARRUÁ 2.8 12V 132cv TDI Diesel,Dezembro/2019,MARRUA
4,4564,2,060003-2,MARRUÁ AM 100 2.8 CS TDI Diesel,NaN,NaN,4564.0,2.0,MARRUÁ AM 100 2.8 CS TDI Diesel,Dezembro/2019,MARRUA
...,...,...,...,...,...,...,...,...,...,...,...
8836,3800,116,516074-0,VM-23 210/ VM 210 6x2 2p (diesel),NaN,NaN,3800.0,116.0,VM-23 210/ VM 210 6x2 2p (diesel),Dezembro/2019,VM-23
8837,3801,116,516075-8,VM-23 240 6x2 2p (diesel),NaN,NaN,3801.0,116.0,VM-23 240 6x2 2p (diesel),Dezembro/2019,VM-23
8838,4572,144,520002-4,Phanter Special Escolar 2p (diesel),NaN,NaN,4572.0,144.0,Phanter Special Escolar 2p (diesel),Dezembro/2019,Phanter
8839,4573,144,520003-2,Phanter Special Exec./Turismo 2p (die.),NaN,NaN,4573.0,144.0,Phanter Special Exec./Turismo 2p (die.),Dezembro/2019,Phanter
8840,4574,144,520001-6,Phanter Special Urbano/SPTRANS 2p (die.),NaN,NaN,4574.0,144.0,Phanter Special Urbano/SPTRANS 2p (die.),Dezembro/2019,Phanter

In [26]:
df.to_excel("teste.xlsx")